coursework/apps/levels/urls.py
from django.urls import path
from . import views

app_name = 'levels'
urlpatterns = [
    path('',views.index,name='index'),
    path('<int:level_id>/',views.level,name='level'),
    path('<int:level_id>/<str:sort_by>/',views.level,name='level'),
]

coursework/urls.py
from django.contrib import admin
from django.urls import path, include
from coursework.routers import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('levels/', include('levels.urls')),
    path('users/', include(router.urls)),
]

coursework/apps/levels/models.py
from django.db import models
from users.models import User

class Level1(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.IntegerField(verbose_name='Очки')
    coins = models.IntegerField(verbose_name='Монеты')
    time = models.IntegerField(verbose_name='Время')
    date = models.DateField(verbose_name='Дата',auto_now_add=True)

    def __str__(self):
        return self.user.login

    class Meta:
        verbose_name = '1 Уровень'
        verbose_name_plural = '1 Уровень'

class Level2(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.IntegerField(verbose_name='Очки')
    coins = models.IntegerField(verbose_name='Монеты')
    time = models.IntegerField(verbose_name='Время')
    date = models.DateField(verbose_name='Дата',auto_now_add=True)

    def __str__(self):
        return self.user.login

    class Meta:
        verbose_name = '2 Уровень'
        verbose_name_plural = '2 Уровень'

class Level3(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.IntegerField(verbose_name='Очки')
    coins = models.IntegerField(verbose_name='Монеты')
    time = models.IntegerField(verbose_name='Время')
    date = models.DateField(verbose_name='Дата',auto_now_add=True)

    def __str__(self):
        return self.user.login

    class Meta:
        verbose_name = '3 Уровень'
        verbose_name_plural = '3 Уровень'

class Level4(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.IntegerField(verbose_name='Очки')
    coins = models.IntegerField(verbose_name='Монеты')
    time = models.IntegerField(verbose_name='Время')
    date = models.DateField(verbose_name='Дата',auto_now_add=True)

    def __str__(self):
        return self.user.login

    class Meta:
        verbose_name = '4 Уровень'
        verbose_name_plural = '4 Уровень'

class Level5(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.IntegerField(verbose_name='Очки')
    coins = models.IntegerField(verbose_name='Монеты')
    time = models.IntegerField(verbose_name='Время')
    date = models.DateField(verbose_name='Дата',auto_now_add=True)

    def __str__(self):
        return self.user.login

    class Meta:
        verbose_name = '5 Уровень'
        verbose_name_plural = '5 Уровень'

coursework/apps/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser,PermissionsMixin

from users.managers import UserManager

class User(AbstractBaseUser,PermissionsMixin):
    login = models.CharField(verbose_name='Логин',max_length=255, unique=True)

    is_active = models.BooleanField(verbose_name='Активирован',default=True)
    is_staff = models.BooleanField(verbose_name='Модератор',default=False)
    is_superuser = models.BooleanField(verbose_name='Администратор',default=False)

    USERNAME_FIELD = 'login'
    # REQUIRED_FIELDS = ['login']

    objects = UserManager()

    def __str__(self):
        return self.login

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

coursework/apps/levels/views.py
from django.shortcuts import render
from .models import Level1,Level2,Level3,Level4,Level5
from django.urls import reverse

def index(request):
    return render(request, 'levels/index.html')

def level(request,level_id,sort_by=''):
    order='-id'
    if sort_by == 'score':
        order='-score'
    if sort_by == 'coins':
        order='-coins'
    if sort_by == 'time':
        order='time'
    if sort_by == 'date':
        order='-date'
    if level_id == 1:
        leaderboard = Level1.objects.order_by(order)
        return render(request, 'levels/leaderboard.html', {'leaderboard': leaderboard,'level_id':level_id})
    if level_id == 2:
        leaderboard = Level2.objects.order_by(order)
        return render(request, 'levels/leaderboard.html', {'leaderboard': leaderboard,'level_id':level_id})
    if level_id == 3:
        leaderboard = Level3.objects.order_by(order)
        return render(request, 'levels/leaderboard.html', {'leaderboard': leaderboard,'level_id':level_id})
    if level_id == 4:
        leaderboard = Level4.objects.order_by(order)
        return render(request, 'levels/leaderboard.html', {'leaderboard': leaderboard,'level_id':level_id})
    if level_id == 5:
        leaderboard = Level5.objects.order_by(order)
        return render(request, 'levels/leaderboard.html', {'leaderboard': leaderboard,'level_id':level_id})

coursework/apps/users/views.py
from rest_framework import serializers
from users.models import User
from rest_framework.viewsets import ModelViewSet
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.exceptions import ValidationError, NotFound, AuthenticationFailed
from rest_framework_simplejwt.tokens import RefreshToken
from rest_framework.permissions import IsAuthenticated



class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ['login','password']
        extra_kwargs = {
            'password':{'write_only':True},
        }
    
    def create(self,validated_data):
        password = validated_data.pop('password', None)
        instance = self.Meta.model(**validated_data)
        if password is not None:
            instance.set_password(password)
        instance.save()
        return instance
        
class UserViewSet(ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

    @action(methods=['POST'], detail=False, url_path='register')
    def register(self,request):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({'message':'success'})

    @action(methods=['POST'], detail=False, url_path='login')
    def login(self,request):
        if 'login' not in request.data:
            raise ValidationError({'error':'empty login'})
        if 'password' not in request.data:
            raise ValidationError({'error':'empty password'})

        try:
            user = User.objects.get(login=request.data['login'])
        except User.DoesNotExist:
            raise NotFound({'error':'no login in user list'})

        if not user.check_password(request.data['password']):
            raise AuthenticationFailed({'error':'wrong password'})

        refresh = RefreshToken.for_user(user)
        response = Response()
        response.data = {'access':str(refresh.access_token)}
        return response

    @action(methods=['GET'], detail=False, permission_classes=[IsAuthenticated],url_path='me')
    def get_user(self, request):
        user = request.user
        data = self.serializer_class(user).data
        return Response(data)

coursework/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Игра{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'print.css' %}" media="print">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body class="bg-light">
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

coursework/templates/levels/index.html
{% extends 'base.html' %}

{% block title %}Уровни{% endblock %}

{% block content %}
        <div class="levels container mt-5 p-2">
            <a class="levels__link col-2 btn btn-primary" href="{% url 'levels:level' 1 %}score">1 Уровень</a>
            <a class="levels__link col-2 btn btn-secondary" href="{% url 'levels:level' 2 %}score">2 Уровень</a>
            <a class="levels__link col-2 btn btn-success" href="{% url 'levels:level' 3 %}score">3 Уровень</a>
            <a class="levels__link col-2 btn btn-danger" href="{% url 'levels:level' 4 %}score">4 Уровень</a>
            <a class="levels__link col-2 btn btn-warning" href="{% url 'levels:level' 5 %}score">5 Уровень</a>
        </div>
{% endblock %}

coursework/templates/levels/leaderboard.html
{% extends 'base.html' %}

{% block title %}{{level_id}} Уровень{% endblock %}

{% block content %}
    {% if leaderboard %}
    <div class="leaderboard container mt-5">
        <div class="row leaderboard__sort">
            <a class="leaderboard__sort-button col btn btn-dark m-2 d-print-none" href="/levels">Назад</a>
            <a class="leaderboard__sort-button col btn btn-dark m-2 d-print-none" href="{% url 'levels:level' level_id %}score">Сортировать по очкам</a>
            <a class="leaderboard__sort-button col btn btn-dark m-2 d-print-none" href="{% url 'levels:level' level_id %}coins">Сортировать по монетам</a>
            <a class="leaderboard__sort-button col btn btn-dark m-2 d-print-none" href="{% url 'levels:level' level_id %}time">Сортировать по времени</a>
            <a class="leaderboard__sort-button col btn btn-dark m-2 d-print-none" href="{% url 'levels:level' level_id %}date">Сортировать по дате</a>
        </div>
        <table class="table table-striped container leaderboard__table">
            <thead>
                <tr class="leaderboard__header">
                    <th class="leaderboard__header-text" scope="col">Nickname</th>
                    <th class="leaderboard__header-text" scope="col">Score</th>
                    <th class="leaderboard__header-text" scope="col">Coins</th>
                    <th class="leaderboard__header-text" scope="col">Time</th>
                    <th class="leaderboard__header-text" scope="col">Date</th>
                </tr>
            </thead>
            <tbody>
        {% for i in leaderboard %}
                <tr class="leaderboard__row">
                    <th class="leaderboard__row-text" scope="row"><a href="/users/">{{i}}</a></th>
                    <td class="leaderboard__row-text">{{i.score}}</td>
                    <td class="leaderboard__row-text">{{i.coins}}</td>
                    <td class="leaderboard__row-text">{{i.time}}</td>
                    <td class="leaderboard__row-text">{{i.date}}</td>
                </tr>
        {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
        Нет результатов
    {% endif %}
{% endblock %}

coursework/templates/users/index.html
{% extends 'base.html' %}

{% block title %}Уровни{% endblock %}

{% block content %}
     <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" name="Зарегистрироваться">
     </form>
{% endblock %}